services:
  - type: web
    name: drowsiness-detection-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
